version: "3.4"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/app/node_modules
    env_file: .env
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:BatSQL12@database:5432/postgres
  database:
    image: postgres:12.15
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "BatSQL12"

volumes:
  gem_cache:
  db_data:
  node_modules:
